model_name: dtc_model
model_path: models/
tree_plot_path: ../data/model_tree_fig.png
csv_url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
deployment_json_name: deployed_model.json

dataset_name: irisdata_raw.csv
dataset_path: ../data/
train_data_name: train_data.csv
validate_data_name: validate_data.csv

dataset_settings:
  header: None

column_names: [sepal length, sepal width, petal length, petal width, class]

features: 
  sepal length: {min: 4.3, max: 7.9}
  sepal width: {min: 2, max: 4.4}
  petal length: {min: 1, max: 6.9}
  petal width: {min: 0.1, max: 2.5}

label_name: class

kfold_settings:
 nr_splits: 5
 shuffle: True
 random_state: 123

report_settings:
  title: Iris Data Profile Report