name: MLflow_Iris_Project

channels:
 - defaults

dependencies:
 - python=3.9.12
 - pandas=1.4.2
 - markupsafe=2.0.0
 - scikit-learn=1.0.2
 - pip
 - pip:
    - mlflow
    - pandas-profiling==3.2.0
    - matplotlib==3.5.2
    - numpy==1.23